version: "3.9"

services:
  app:
    build: .
    container_name: durian-backend
    ports:
      - "8088:5000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      # override DB to use local MySQL container
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: HosbaDurianSystem
      DB_USERNAME: root
      DB_PASSWORD: root

      # IMPORTANT: disable DB_URL so Laravel won't force PostgreSQL
      DB_URL: ""

      # sessions stored in DB (needs migrate)
      SESSION_DRIVER: database

    command: php artisan serve --host=0.0.0.0 --port=5000

  db:
    image: mysql:8.0
    container_name: durian-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: HosbaDurianSystem
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
